#!/usr/bin/env bash
# Auralis — one-command local dev startup.
#
# Spawns three background services:
#   1. substrate-contracts-node --dev (pallet-contracts v9+ runtime)
#   2. Ollama daemon (for AI Requester + Reviewer agents)
#   3. Next.js frontend (http://localhost:3000)
#
# Logs are written to .logs/ for inspection. PIDs are tracked so that
# `./scripts/stop.sh` can clean up everything in one go.
#
# Usage:  ./scripts/start.sh
#
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOGDIR="$ROOT/.logs"
PIDDIR="$ROOT/.logs/pids"

mkdir -p "$LOGDIR" "$PIDDIR"

NODE_LOG="$LOGDIR/substrate-node.log"
OLLAMA_LOG="$LOGDIR/ollama.log"
FRONTEND_LOG="$LOGDIR/frontend.log"

NODE_PID_FILE="$PIDDIR/substrate-node.pid"
OLLAMA_PID_FILE="$PIDDIR/ollama.pid"
FRONTEND_PID_FILE="$PIDDIR/frontend.pid"

# ── Pre-flight ──────────────────────────────────────────────────────────
echo "→ Checking prerequisites..."
"$ROOT/scripts/check-prereqs.sh" || {
  echo "✗ Prerequisite check failed. Fix the above and re-run."
  exit 1
}
echo

# ── Cleanup any stale processes from a previous run ─────────────────────
cleanup_stale() {
  for pidfile in "$NODE_PID_FILE" "$OLLAMA_PID_FILE" "$FRONTEND_PID_FILE"; do
    if [ -f "$pidfile" ]; then
      pid=$(cat "$pidfile" 2>/dev/null || true)
      if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        echo "→ Killing stale process (pid $pid)..."
        kill "$pid" 2>/dev/null || true
        sleep 0.5
      fi
      rm -f "$pidfile"
    fi
  done
}
cleanup_stale

# ── Helper: wait until a TCP port is accepting connections ─────────────
wait_port() {
  local host="$1"; local port="$2"; local what="$3"
  local i=0
  while ! (echo > "/dev/tcp/$host/$port") 2>/dev/null; do
    i=$((i + 1))
    if [ "$i" -gt 60 ]; then
      echo "✗ Timeout waiting for $what on $host:$port"
      return 1
    fi
    sleep 0.5
  done
}

# ── 1. Substrate node ───────────────────────────────────────────────────
echo "→ Starting substrate-contracts-node..."
nohup substrate-contracts-node \
  --dev \
  --tmp \
  >"$NODE_LOG" 2>&1 &
node_pid=$!
echo "$node_pid" > "$NODE_PID_FILE"

# Wait for RPC port
if ! wait_port 127.0.0.1 9944 "substrate node RPC"; then
  echo "✗ Node failed to start. See $NODE_LOG"
  tail -30 "$NODE_LOG"
  exit 1
fi
echo "  ✓ Node up (pid $node_pid, port 9944)"
echo "  ✓ Log: $NODE_LOG"

# ── 2. Ollama daemon ────────────────────────────────────────────────────
echo "→ Starting Ollama daemon..."
if (echo > /dev/tcp/127.0.0.1/11434) 2>/dev/null; then
  echo "  ✓ Ollama already running (port 11434)"
else
  if ! command -v ollama >/dev/null 2>&1; then
    echo "  ⚠️  ollama not installed. AI agents will fall back to seeded mock data."
    echo "      Install: brew install ollama  (then re-run start.sh)"
  else
    nohup ollama serve >"$OLLAMA_LOG" 2>&1 &
    ollama_pid=$!
    echo "$ollama_pid" > "$OLLAMA_PID_FILE"
    if wait_port 127.0.0.1 11434 "Ollama daemon"; then
      echo "  ✓ Ollama up (pid $ollama_pid, port 11434)"
      echo "  ✓ Log: $OLLAMA_LOG"
      # Pull model if missing — runs in background, non-blocking
      MODEL="${OLLAMA_MODEL:-llama3.2}"
      if ! ollama list 2>/dev/null | grep -q "$MODEL"; then
        echo "  → Pulling model $MODEL (first time only, ~2GB)..."
        ollama pull "$MODEL" || echo "  ⚠️  Model pull failed. Try manually: ollama pull $MODEL"
      fi
    else
      echo "  ⚠️  Ollama didn't come up. Continuing without AI."
    fi
  fi
fi

# ── 3. Frontend env ─────────────────────────────────────────────────────
ENV_FILE="$ROOT/frontend/.env.local"
if [ ! -f "$ENV_FILE" ]; then
  echo "→ Creating frontend/.env.local from defaults..."
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/start.sh
# Edit to switch endpoints / model. Re-run start.sh after edits.

NEXT_PUBLIC_PORTALDOT_WS=ws://127.0.0.1:9944

OLLAMA_HOST=http://localhost:11434
OLLAMA_MODEL=llama3.2
OLLAMA_KEY=
EOF
  echo "  ✓ Wrote $ENV_FILE"
fi

# ── 4. Frontend npm install (skipped if up-to-date) ────────────────────
if [ ! -d "$ROOT/frontend/node_modules" ]; then
  echo "→ Installing frontend dependencies (first run)..."
  (cd "$ROOT/frontend" && npm install)
fi

# ── 5. Frontend dev server ──────────────────────────────────────────────
echo "→ Starting Next.js frontend..."
(cd "$ROOT/frontend" && nohup npm run dev >"$FRONTEND_LOG" 2>&1 &)
sleep 2
# Find the npm process pid (best-effort)
frontend_pid=$(pgrep -f "next dev" | head -1 || true)
if [ -n "$frontend_pid" ]; then
  echo "$frontend_pid" > "$FRONTEND_PID_FILE"
fi

if ! wait_port 127.0.0.1 3000 "Next.js dev server"; then
  echo "✗ Frontend failed to start. See $FRONTEND_LOG"
  tail -30 "$FRONTEND_LOG"
  exit 1
fi
echo "  ✓ Frontend up (port 3000)"
echo "  ✓ Log: $FRONTEND_LOG"

# ── Summary ─────────────────────────────────────────────────────────────
cat <<EOF

✅ All services up.

  Substrate node : ws://127.0.0.1:9944    (manual-seal, instant block on tx)
  Ollama daemon  : http://localhost:11434  (model: ${OLLAMA_MODEL:-llama3.2})
  Frontend       : http://localhost:3000

  Logs are in $LOGDIR
  PIDs are in $PIDDIR

Open http://localhost:3000 in your browser, sign in as Alice, and try
the demo flow (create group → deposit → request → vote).

To stop everything cleanly: ./scripts/stop.sh
EOF
